# Generated by Django 3.2.23 on 2026-09-29 13:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targetApp', '0001_initial'),
        ('scanEngine', '0002_hackerone_send_report'),
        ('startScan', '0002_auto_20240911_0145'),
        ('dashboard', '0002_chaosapikey_hackeroneapikey_inappnotification_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('status', models.IntegerField(choices=[(-1, 'Pending'), (0, 'Failed'), (1, 'Running'), (2, 'Completed'), (3, 'Stopped'), (4, 'Paused')], default=-1)),
                ('batch_size', models.IntegerField(default=5)),
                ('tick_interval_seconds', models.IntegerField(default=30)),
                ('max_runtime_minutes', models.IntegerField(default=1440)),
                ('cfg_out_of_scope_subdomains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('next_tick_eta', models.DateTimeField(blank=True, null=True)),
                ('tick_lock_token', models.CharField(blank=True, max_length=64, null=True)),
                ('tick_locked_at', models.DateTimeField(blank=True, null=True)),
                ('domains', models.ManyToManyField(related_name='assessments', to='targetApp.Domain')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanEngine.enginetype')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointClassification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('auth', 'Authentication/Authorization'), ('access_control', 'Access control / IDOR candidate'), ('injection', 'Injection candidate'), ('xss', 'XSS candidate'), ('ssrf', 'SSRF candidate'), ('file_upload_download', 'File upload/download'), ('path_traversal', 'Path traversal'), ('api', 'API endpoint'), ('info_exposure', 'Sensitive information exposure'), ('misconfig', 'Misconfiguration'), ('admin', 'Admin/management interface'), ('debug_dev', 'Debug/development endpoint'), ('cloud_storage', 'Cloud/storage exposure'), ('open_redirect', 'Open redirect')], max_length=40)),
                ('signals', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='multiScan.assessment')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.endpoint')),
            ],
            options={
                'unique_together': {('assessment', 'endpoint', 'category')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentDomainRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('batch_index', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_runs', to='multiScan.assessment')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.scanhistory')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('assessment', 'domain')},
            },
        ),
    ]
