# Generated by Django 3.2.23 on 2026-09-22 15:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanEngine', '0002_hackerone_send_report'),
        ('startScan', '0002_auto_20240911_0145'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.IntegerField(choices=[(1, 'AI-Assisted'), (2, 'Autonomous')])),
                ('risk_level', models.IntegerField(choices=[(0, 'Safe'), (1, 'Standard'), (2, 'Controlled')], default=0)),
                ('status', models.IntegerField(choices=[(-1, 'Pending'), (0, 'Failed'), (1, 'Running'), (2, 'Completed'), (3, 'Stopped'), (4, 'Paused')], default=-1)),
                ('max_runtime_minutes', models.IntegerField(default=240)),
                ('max_actions', models.IntegerField(default=50)),
                ('actions_per_tick', models.IntegerField(default=2)),
                ('tick_interval_seconds', models.IntegerField(default=30)),
                ('failure_threshold', models.IntegerField(default=5)),
                ('actions_taken_count', models.IntegerField(default=0)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('cfg_out_of_scope_subdomains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('cfg_imported_subdomains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('cfg_starting_point_path', models.CharField(blank=True, max_length=200, null=True)),
                ('cfg_excluded_paths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('next_tick_eta', models.DateTimeField(blank=True, null=True)),
                ('tick_lock_token', models.CharField(blank=True, max_length=64, null=True)),
                ('tick_locked_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomous_assessments', to='targetApp.domain')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanEngine.enginetype')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomous_assessments', to=settings.AUTH_USER_MODEL)),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(max_length=100)),
                ('candidate_score', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('policy_check', models.JSONField(default=dict)),
                ('policy_result', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked'), ('requires_approval', 'Requires approval')], default='allowed', max_length=20)),
                ('policy_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_result_status', models.IntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_decisions', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='autonomousMode.autonomousassessment')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.endpoint')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.subdomain')),
                ('subscan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.subscan')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('assessment', 'sequence')},
            },
        ),
    ]
