# Generated by Django 3.2.23 on 2026-09-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targetApp', '0001_initial'),
        ('startScan', '0002_auto_20240911_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('is_likely_false_positive', models.BooleanField(default=False)),
                ('rationale', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finding_score', to='startScan.vulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='OriginIpCandidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('source', models.CharField(max_length=50)),
                ('confidence', models.IntegerField(default=0)),
                ('is_behind_cdn_bypass', models.BooleanField(default=False)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
            options={
                'unique_together': {('scan_history', 'domain', 'ip_address', 'source')},
            },
        ),
        migrations.CreateModel(
            name='HttpParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('param_type', models.CharField(choices=[('query', 'Query'), ('body', 'Body'), ('json', 'JSON')], default='query', max_length=20)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.endpoint')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
            ],
            options={
                'unique_together': {('endpoint', 'name', 'param_type')},
            },
        ),
        migrations.CreateModel(
            name='DiscoveredSecret',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_type', models.CharField(max_length=100)),
                ('severity', models.IntegerField(choices=[(0, 'Info'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('redacted_snippet', models.CharField(max_length=500)),
                ('source_url', models.CharField(blank=True, max_length=10000, null=True)),
                ('discovered_date', models.DateTimeField(blank=True, null=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.endpoint')),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
            ],
            options={
                'unique_together': {('scan_history', 'secret_type', 'redacted_snippet', 'source_url')},
            },
        ),
    ]
